repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.23  # Use the latest stable version
    hooks:
      - id: actionlint

  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8